server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL

SLAB:
  filePath: D:/gitFile/github/ZXJS #OUTPR4 文件位置

security:
  enabled: false

#windows共享文件
share:
  ip: 127.0.0.1 #共享机器的ip
  username: yan #共享文件夹的用户名
  password: 123 #共享文件夹的密码
  dir: logs #共享文件夹的目录
  filename: modelInfos.log #共享文件名