server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://10.10.3.1:5432/hrmw
    username: postgres
    password: Axpgadmin12#$
  servlet:
    multipart:
      enabled: true #是否支持multipart上传文件
      max-file-size: 100MB #单个文件的最大上限
      max-request-size: 110MB #单个请求的文件总大小上限
  security:
    user:
      name: admin
      password: admins