server:
  port: 8088
  servlet:
    context-path: /

spring:
  datasource:
    url: jdbc:postgresql://10.10.3.1:5432/hrmw
    username: postgres
    password: Axpgadmin12#$
  data:
    mongodb:
      uri: mongodb://localhost:27017/test
      username:
      password:

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印SQL
